valor_original = float(input())
print("NOTAS:")
print("{} nota(s) de R$ 100.00".format(int(valor_original/100)))
valor_sobrou = round(valor_original%100, 2)
print("{} nota(s) de R$ 50.00".format(int(valor_sobrou/50)))
valor_sobrou = round(valor_sobrou%50, 2)
print("{} nota(s) de R$ 20.00".format(int(valor_sobrou/20)))
valor_sobrou = round(valor_sobrou%20, 2)
print("{} nota(s) de R$ 10.00".format(int(valor_sobrou/10)))
valor_sobrou = round(valor_sobrou%10, 2)
print("{} nota(s) de R$ 5.00".format(int(valor_sobrou/5)))
valor_sobrou = round(valor_sobrou%5, 2)
print("{} nota(s) de R$ 2.00".format(int(valor_sobrou/2)))
valor_sobrou = round(valor_sobrou%2, 2)
print("MOEDAS:")
print("{} moeda(s) de R$ 1.00".format(int(valor_sobrou/1)))
valor_sobrou = round(valor_sobrou%1, 2)
print("{} moeda(s) de R$ 0.50".format(int(valor_sobrou/0.5)))
valor_sobrou = round(valor_sobrou%0.5, 2)
print("{} moeda(s) de R$ 0.25".format(int(valor_sobrou/0.25)))
valor_sobrou = round(valor_sobrou%0.25, 2)
print("{} moeda(s) de R$ 0.10".format(int(valor_sobrou/0.10)))
valor_sobrou = round(valor_sobrou%0.10, 2)
print("{} moeda(s) de R$ 0.05".format(int(valor_sobrou/0.05)))
valor_sobrou = round(valor_sobrou%0.05, 2)
print("{} moeda(s) de R$ 0.01".format(int(valor_sobrou/0.01)))
